repos:
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        name: markdownlint
        entry: markdownlint --config .markdownlint.json
        language: node
        types: [markdown]
        files: \.(md|markdown)$
        pass_filenames: true
        additional_dependencies: []
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: prettier-markdown
        entry: prettier --write
        language: node
        types: [markdown]
        files: \.(md|markdown)$