site_name: Cargo Bikes Vault
site_description: A comprehensive knowledge base for cargo bikes, with focus on long-tail cargo bikes
site_url: https://pavelzbornik.github.io/cargo-bikes/
repo_url: https://github.com/pavelzbornik/cargo-bikes
edit_uri: edit/main/vault/notes/
theme:
  name: material
  icon:
    logo: material/motorbike-electric
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      # Palette toggle for light mode

      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      # Palette toggle for dark mode

      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.action.edit
    - content.tooltips
plugins:
  - tags
  - search
  - obsidian-bridge
  - git-revision-date
  - git-authors
  - glightbox
  - table-reader
  - redirects
  - section-index
  - llmstxt:
      markdown_description: |
        A comprehensive knowledge base for cargo bikes, with focus on long-tail cargo bikes,
        designs, specifications, maintenance tips, and community contributions.
      sections:
        Bike Models:
          - bikes/index.md: Overview of all bike models
          - bikes/*/*.md
markdown_extensions:
  - meta
  - toc:
      permalink: true
  - tables
  - attr_list
  - md_in_html
  # Obsidian-like features provided by mkdocs-obsidian-bridge

  - obsidian_media_mkdocs
  - obsidian_callouts
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pavelzbornik/cargo-bikes
docs_dir: vault/notes
site_dir: site
