name: Update Bike Notes

on:
  schedule:
    # Run weekly on Sunday at 2 AM UTC
    - cron: "0 2 * * 0"
  workflow_dispatch:
    inputs:
      brand:
        description: "Brand to update (leave empty for all)"
        required: false
        type: string
      validate_only:
        description: "Validate only, don't update"
        required: false
        type: boolean
        default: false
      dry_run:
        description: "Dry run mode (preview changes)"
        required: false
        type: boolean
        default: false

permissions:
  contents: write
  pull-requests: write

jobs:
  update-notes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      
      - name: Validate all notes (pre-check)
        run: |
          PYTHONPATH=. python -m scripts.bike_note_updater.cli validate-all-notes
        continue-on-error: true
      
      - name: Update bike notes
        if: ${{ !inputs.validate_only }}
        run: |
          BRAND_FLAG=""
          if [ -n "${{ inputs.brand }}" ]; then
            BRAND_FLAG="--brand ${{ inputs.brand }}"
          fi
          
          DRY_RUN_FLAG=""
          if [ "${{ inputs.dry_run }}" = "true" ]; then
            DRY_RUN_FLAG="--dry-run"
          fi
          
          PYTHONPATH=. python -m scripts.bike_note_updater.cli update-all-bikes \
            $BRAND_FLAG $DRY_RUN_FLAG
      
      - name: Validate updated notes (post-check)
        if: ${{ !inputs.validate_only && !inputs.dry_run }}
        run: |
          PYTHONPATH=. python -m scripts.bike_note_updater.cli validate-all-notes
      
      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Create Pull Request
        if: steps.check_changes.outputs.has_changes == 'true' && !inputs.dry_run && github.event_name == 'schedule'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: auto-update bike notes from manufacturer pages"
          title: "chore: auto-update bike notes"
          body: |
            ## Automated Bike Note Updates
            
            This PR contains automated updates to bike notes fetched from manufacturer product pages.
            
            ### Changes Made
            - Updated specifications from product pages
            - Updated reseller pricing and availability
            - Validated all notes against BIKE_SPECS_SCHEMA
            
            ### Review Checklist
            - [ ] Review flagged conflicts in commit message
            - [ ] Verify significant spec changes are accurate
            - [ ] Check that user-added content was preserved
            
            **Generated by**: Bike Note Updater Agent
            **Workflow run**: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          branch: auto-update-bike-notes
          delete-branch: true
      
      - name: Commit changes directly
        if: steps.check_changes.outputs.has_changes == 'true' && !inputs.dry_run && github.event_name != 'schedule'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: update bike notes [skip ci]"
          git push
      
      - name: Upload validation report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: validation-report
          path: |
            validation-report.txt
          retention-days: 7
